### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by 89z** [tombulled/innertube#4] opened 2021-08-25 23:02 UTC
The README instruction did not work for me. If anyone having same problem, this fixed it:

~~~
pip install attr
pip install furl
pip install git+https://github.com/tombulled/mime
pip install git+https://github.com/tombulled/register
pip install git+https://github.com/tombulled/sets
pip install git+https://github.com/tombulled/useragent
pip install parse
pip install requests
pip install toolz
~~~

**Comment by tombulled** [comment] 2021-09-08 19:56
Hey, thanks for bringing this to my attention! I believe this issue was caused by a dependency conflict for `attrs`. I've merged the `dev` branch which should hopefully fix this issue. If possible, please can you confirm if this issue has been resolved on your end :slightly_smiling_face:

**Comment by 89z** [comment] 2021-09-08 20:47
Since I dont know when I will have your attention again (its been 2 weeks), Id like to take this opportunity to ask a question. Can you clarify how you came about these version numbers:

https://github.com/tombulled/innertube/blob/d68516c8229bd5c5667435711525af8527a582d4/innertube/infos.py#L124-L152

I am trying to automate the process of checking the latest version, I think I figured it out, but if any better method is available I would be interested.

**Comment by tombulled** [comment] 2021-09-08 20:50
I have been manually collecting the version numbers by intercepting and inspecting network traffic rather than using an automated approach.

**Comment by tombulled** [comment] 2021-09-08 20:54
Feel free to let me know if this issue persists and I will investigate it in my own time. Regards.

**Closed by tombulled** 2021-09-08 20:54 UTC
